### ISSUE TITLE
Reduce log output when testing

### ISSUE THREAD

**Issue by dandanlen** [diffix/explorer#165]
The test logs output a lot of `info` and `debug` messages which makes it really hard to see which test has failed and why, for example when a Travis build fails. 

We should disable asp.net logging during test runs.

example:
```
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]

      Request starting HTTP/1.1 POST http://localhost/explore application/json 

  √ Explorer.Api.Tests.ApiTests.FailWithBadMethod(method: "DELETE") [15ms]

  √ Explorer.Api.Tests.ApiTests.FailWithBadMethod(method: "PUT") [1ms]

  √ Explorer.Api.Tests.ApiTests.FailWithBadEndPoint(endpoint: "/invalid endpoint test") [4ms]

dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1001]

      2 candidate(s) found for the request path '/explore'

  √ Explorer.Api.Tests.ApiTests.FailWithBadEndPoint(endpoint: "") [1ms]

  √ Explorer.Api.Tests.ApiTests.FailWithBadEndPoint(endpoint: "/") [1ms]

  √ Explorer.Api.Tests.ApiTests.FailWithEmptyFields [21ms]

dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1005]

      Endpoint 'Explorer.Api.Controllers.ExploreController.Explore (explorer.api)' with route pattern 'explore' is valid for the request path '/explore'

  X Explorer.Api.Tests.ApiTests.FailWithInvalidApiKey [31ms]

dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1005]

      Endpoint 'Explorer.Api.Controllers.ExploreController.OtherActions (explorer.api)' with route pattern '{**catchall}' is valid for the request path '/explore'

  Error Message:

   Assert.Equal() Failure

Expected: InternalServerError

Actual:   OK

  Stack Trace:

     at Explorer.Api.Tests.ApiTests.<>c.<FailWithInvalidApiKey>b__12_0(HttpResponseMessage response, String content) in /home/travis/build/diffix/explorer/tests/explorer.api.tests/ApiTests.cs:line 191

   at Explorer.Api.Tests.ApiTests.TestApi(HttpMethod method, String endpoint, Object data, ApiTestActionWithContent test, String vcrSessionName) in /home/travis/build/diffix/explorer/tests/explorer.api.tests/ApiTests.cs:line 205

   at Explorer.Api.Tests.ApiTests.FailWithInvalidApiKey() in /home/travis/build/diffix/explorer/tests/explorer.api.tests/ApiTests.cs:line 185

--- End of stack trace from previous location where exception was thrown ---

dbug: Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware[1]

      Request matched endpoint 'Explorer.Api.Controllers.ExploreController.Explore (explorer.api)'

info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]

      Executing endpoint 'Explorer.Api.Controllers.ExploreController.Explore (explorer.api)'

info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]

      Route matched with {action = "Explore", controller = "Explore"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Explore(Explorer.Api.Models.ExploreParams, Explorer.ExplorationLauncher, Aircloak.JsonApi.IAircloakAuthenticationProvider, Explorer.Api.ContextBuilder, Explorer.Api.AircloakConnectionBuilder) on controller Explorer.Api.Controllers.ExploreController (explorer.api).

dbug: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[1]

      Execution plan of authorization filters (in the following order): None

dbug: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[1]

      Execution plan of resource filters (in the following order): None

dbug: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[1]

      Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Infrastructure.ModelStateInvalidFilter (Order: -2000)

dbug: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[1]

      Execution plan of exception filters (in the following order): None

dbug: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[1]

      Execution plan of result filters (in the following order): Microsoft.AspNetCore.Mvc.Infrastructure.ClientErrorResultFilter (Order: -2000), Microsoft.AspNetCore.Mvc.ProducesAttribute (Order: 0)

dbug: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[1]

      Executing controller factory for controller Explorer.Api.Controllers.ExploreController (explorer.api)

dbug: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]

      Executed controller factory for controller Explorer.Api.Controllers.ExploreController (explorer.api)

dbug: Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder[22]

      Attempting to bind parameter 'data' of type 'Explorer.Api.Models.ExploreParams' ...
```

**Comment by dandanlen** [comment]
This was addressed in #177 by changing the default log levels in appsettings.Test.json
