### ISSUE TITLE
"This container has been disposed" bug

### ISSUE THREAD

**Issue by sebastian** [diffix/explorer#309]
I am trying to run analyses locally on my system. Using the latest master (8123519) at the time of writing.
When trying to run an analysis I get a lot of the following error message:

```
[2020-09-23 16:19:39] fail: Explorer.Api.Controllers.ExploreController[0]
      Exception occurred in exploration task.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'This Container has been disposed'.
   at Lamar.IoC.Scope.assertNotDisposed()
   at Lamar.Container.GetNestedContainer()
   at Explorer.Exploration.<RunTask>b__22_2(ExplorerContext context) in /Users/sebastian/work-projects/explorer/src/explorer/Exploration.cs:line 85
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at System.Collections.Immutable.ImmutableArray.ToImmutableArray[TSource](IEnumerable`1 items)
   at Explorer.Exploration.<RunTask>b__22_0() in /Users/sebastian/work-projects/explorer/src/explorer/Exploration.cs:line 82
   at Explorer.Exploration.RunStage(ExplorationStatus initialStatus, Func`1 t) in /Users/sebastian/work-projects/explorer/src/explorer/Exploration.cs:line 106
   at Explorer.Exploration.RunTask() in /Users/sebastian/work-projects/explorer/src/explorer/Exploration.cs:line 75
   at Explorer.Api.Controllers.ExploreController.Result(Guid explorationId) in /Users/sebastian/work-projects/explorer/src/explorer.api/Controllers/ExploreController.cs:line 91
```

**Comment by sebastian** [comment]
Sentry error: https://sentry.io/organizations/aircloak/issues/1895339827/?environment=Production&project=5339378&referrer=alert_email

**Comment by dandanlen** [comment]
Sorry, forgot to reply to this issue... we're aware of this bug and it's fixed in a soon-to-merged branch. 
We're not sure how it slipped through travis tests - possibly due to request caching in the vcr. 

In the meantime you can use the preivous commit (af92ca7ce75ac3badf463df46e09b3335c2f640c), it should be functionally equivalent.
